package sandbox

import (
	"context"
	"crypto/rand"
	"crypto/subtle"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"
	"sync"
	"time"

	"scratchpad/internal/browser"
	"scratchpad/internal/engine"
	"scratchpad/internal/protocol"

	"github.com/google/uuid"
)

// Session holds all state for a single connected agent.
type Session struct {
	ID   string
	Kind engine.Kind

	// CreatedAt is when the session was created; exposed via session_list /
	// session_snapshot so agents can reason about session age.
	CreatedAt time.Time

	// Persistent marks a session as persistent (improvement-plan item 22): the
	// manager's idle-cleanup loop never reaps it, so scratchpad-cli resume can
	// restore it by profile directory. Set from engine.Options.Persistent.
	Persistent bool

	Engine      engine.Engine // interface — could be Chrome, Android, etc.
	SessionLogs []protocol.ConsoleLog
	LogMu       sync.Mutex
	LastTree    []protocol.SpatialNode

	// Engines holds the per-context engines of a hybrid session (improvement-plan
	// item 31), keyed by context name ("web", "android"). Nil for single-platform
	// sessions, where Engine alone holds the one engine. Guarded by ctxMu.
	Engines map[string]engine.Engine

	// ActiveContext names the currently active context of a hybrid session
	// (improvement-plan item 31), e.g. "web" or "android". "" for single-platform
	// sessions. Guarded by ctxMu; Engine always mirrors the active context's
	// engine so existing dispatch layers route without changes.
	ActiveContext string

	// ctxMu guards Engines, ActiveContext, and the Engine mirror so context
	// switching (executor goroutine) never races Close()/ListSessions reads.
	ctxMu sync.Mutex

	// LastActivity is updated every time the session receives a message.
	// Used by the cleanup loop to detect and close idle sessions.
	// It is guarded by activityMu: websocket goroutines call Touch while the
	// manager's cleanup loop reads the timestamp to decide eviction.
	activityMu   sync.Mutex
	LastActivity time.Time

	// inFlight tracks whether an action is currently executing on this session.
	// Guarded by actionMu. The cleanup loop skips sessions with an in-flight
	// action so a mid-action session is never reaped from underneath the action.
	actionMu sync.Mutex
	inFlight bool

	// Limits carries this session's resource budgets and guardrails (item 36).
	// It is applied by the Manager at creation; zero values mean "no limit".
	Limits Limits

	// steps counts executed actions toward MaxTotalSteps. Guarded by stepsMu.
	stepsMu sync.Mutex
	steps   int

	// lastObserve records the last observation time for ObserveThrottle pacing.
	observeMu   sync.Mutex
	lastObserve time.Time

	// ConsoleRing stores recent console logs for observability endpoints.
	// It is appended during WebSocket observation cycles.
	ConsoleRing      []protocol.ConsoleLog
	ConsoleRingLimit int

	// Recorder captures every action step to an append-only JSONL timeline
	// under SCRATCHPAD_TRACE_DIR. Only set for browser-kind sessions; nil for
	// platforms that have no timeline recorder. Writes are mutex-guarded
	// inside the recorder, so it is safe to feed from the websocket goroutine
	// while the CDP event loop also writes via the engine listener.
	Recorder *browser.ActionRecorder

	// Events is the session's typed event bus (improvement-plan item 34).
	// Engines publish raw events through an AddListener-wired translator
	// (browser.NewEventPublisher); transports publish observe_complete via
	// PublishObserveComplete. WS push, SSE, and wait_for_event all consume it.
	Events *EventBus

	// Capability is the per-session owner secret (improvement-plan item 35).
	// It is generated by the manager when capability isolation is enabled (a
	// token is configured and shared sessions are not allowed), and returned to
	// the session's creator in the WS handshake / HTTP create response. Attach
	// and the SSE stream require it, so only the creator can drive the session.
	// Empty when isolation is off, in which case the session is shared.
	Capability string
}

// CheckCapability reports whether cap matches the session's owner secret using
// a constant-time compare. A session with no capability (isolation off) is
// always accessible; a missing capability never matches a set one.
func (s *Session) CheckCapability(cap string) bool {
	if s.Capability == "" {
		return true
	}
	if cap == "" {
		return false
	}
	return subtle.ConstantTimeCompare([]byte(s.Capability), []byte(cap)) == 1
}

// LastActivityAt returns the last-activity timestamp, synchronized so the
// manager's cleanup loop can read it safely while websocket goroutines Touch.
func (s *Session) LastActivityAt() time.Time {
	s.activityMu.Lock()
	la := s.LastActivity
	s.activityMu.Unlock()
	return la
}

// IsExpired returns true when the session has been idle for longer than the
// given timeout. Used by the Manager's cleanup loop to sweep stale sessions.
func (s *Session) IsExpired(timeout time.Duration) bool {
	return time.Since(s.LastActivityAt()) > timeout
}

// Touch updates the LastActivity timestamp to now, marking the session as
// recently used. Call this whenever the session processes a message, and when
// a client attaches to the session (the "keep alive" lease).
func (s *Session) Touch() {
	s.activityMu.Lock()
	s.LastActivity = time.Now()
	s.activityMu.Unlock()
}

// BeginAction marks the session as running an action. It returns false when
// another action is already in flight (callers should not start a second one).
func (s *Session) BeginAction() bool {
	s.actionMu.Lock()
	defer s.actionMu.Unlock()
	if s.inFlight {
		return false
	}
	s.inFlight = true
	return true
}

// EndAction clears the in-flight marker for the session.
func (s *Session) EndAction() {
	s.actionMu.Lock()
	s.inFlight = false
	s.actionMu.Unlock()
}

// HasActiveAction reports whether an action is currently executing on the
// session. Used by the Manager's cleanup loop to avoid reaping a mid-action
// session.
func (s *Session) HasActiveAction() bool {
	s.actionMu.Lock()
	defer s.actionMu.Unlock()
	return s.inFlight
}

// GuardStep enforces the max_total_steps guardrail: it increments the session's
// step counter and returns protocol.ErrGuardrailHit when the session is at or
// over its step cap. A nil/zero cap never blocks.
func (s *Session) GuardStep() error {
	if s.Limits.MaxTotalSteps <= 0 {
		return nil
	}
	s.stepsMu.Lock()
	defer s.stepsMu.Unlock()
	if s.steps >= s.Limits.MaxTotalSteps {
		return protocol.ErrGuardrailHit
	}
	s.steps++
	return nil
}

// ActionTimeout wraps parent with the session's max_action_duration timeout.
// Without a configured duration it returns a cancellable context with the same
// semantics as context.WithCancel. The returned cancel must be called when the
// action completes.
func (s *Session) ActionTimeout(parent context.Context) (context.Context, context.CancelFunc) {
	if s.Limits.MaxActionDuration > 0 {
		return context.WithTimeout(parent, s.Limits.MaxActionDuration)
	}
	return context.WithCancel(parent)
}

// ThrottleObserve paces observations against the session's ObserveThrottle
// minimum spacing. It blocks until the next observation is allowed, then
// records the new observation time. A nil/zero throttle never blocks.
func (s *Session) ThrottleObserve() {
	if s.Limits.ObserveThrottle <= 0 {
		return
	}
	s.observeMu.Lock()
	defer s.observeMu.Unlock()
	elapsed := time.Since(s.lastObserve)
	if wait := s.Limits.ObserveThrottle - elapsed; wait > 0 {
		time.Sleep(wait)
	}
	s.lastObserve = time.Now()
}

// ActiveEngine returns the engine of the session's active context. For
// single-platform sessions this is the session's one engine. Dispatch layers
// can route through this (or the Session.Engine mirror) so actions land on the
// active context of a hybrid session (improvement-plan item 31).
func (s *Session) ActiveEngine() engine.Engine {
	s.ctxMu.Lock()
	defer s.ctxMu.Unlock()
	return s.Engine
}

// ActiveContextName returns the name of the active context ("" for
// single-platform sessions).
func (s *Session) ActiveContextName() string {
	s.ctxMu.Lock()
	defer s.ctxMu.Unlock()
	return s.ActiveContext
}

// PublishEvent pushes a typed event onto the session's bus, stamped with the
// session id. data is marshaled into the event payload; nil yields an empty
// payload. A nil bus (defensive; sessions always have one) is a no-op.
func (s *Session) PublishEvent(t string, data any) {
	if s.Events == nil {
		return
	}
	var raw json.RawMessage
	if data != nil {
		if b, err := json.Marshal(data); err == nil {
			raw = b
		}
	}
	s.Events.Publish(protocol.Event{Type: t, SessionID: s.ID, Data: raw})
}

// PublishObserveComplete emits the observe_complete tick after a successful
// observation so subscribers can react without polling (improvement-plan item
// 34). The payload carries a light page snapshot (url + node count) when the
// caller supplies an observation.
func (s *Session) PublishObserveComplete(obs *protocol.ObservationResponse) {
	if s.Events == nil {
		return
	}
	data := map[string]any{}
	if obs != nil {
		if obs.PageInfo != nil {
			data["url"] = obs.PageInfo.URL
		}
		data["node_count"] = len(obs.SpatialTree)
	}
	s.PublishEvent(protocol.EventObserveComplete, data)
}

// Contexts returns the context names of a hybrid session, sorted for
// determinism. Nil for single-platform sessions.
func (s *Session) Contexts() []string {
	s.ctxMu.Lock()
	defer s.ctxMu.Unlock()
	if len(s.Engines) == 0 {
		return nil
	}
	return s.contextNamesLocked()
}

// contextNamesLocked returns the sorted context names of a hybrid session.
// Callers must hold ctxMu.
func (s *Session) contextNamesLocked() []string {
	names := make([]string, 0, len(s.Engines))
	for name := range s.Engines {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// SetContext switches the active context of a hybrid session (improvement-plan
// item 31). It returns a clean error when the context is unknown or the session
// has no other context (single-platform). The switch resets the delta base so
// the next observation is a full tree rather than a cross-platform diff.
func (s *Session) SetContext(name string) error {
	s.ctxMu.Lock()
	defer s.ctxMu.Unlock()
	if len(s.Engines) == 0 {
		return fmt.Errorf("set_context: session %q has a single platform; nothing to switch", s.ID)
	}
	eng, ok := s.Engines[name]
	if !ok {
		return fmt.Errorf("set_context: unknown context %q (have %v)", name, s.contextNamesLocked())
	}
	s.ActiveContext = name
	s.Engine = eng
	s.LastTree = nil
	return nil
}

// CreateSession instantiates a brand-new engine of the requested Kind and
// registers the session in the manager's map.
// The caller is responsible for calling DeleteSession when the agent disconnects.
//
// mods are applied to a copy of opts before any engine work. The only modifier
// is engine.WithEngines, which supplies pre-built engines for a hybrid session
// (improvement-plan item 31) and skips the registry entirely. When opts carries
// a Platforms list instead, one engine per platform is instantiated.
func (m *Manager) CreateSession(kind engine.Kind, opts engine.Options, mods ...func(*engine.Options)) (*Session, error) {
	for _, mod := range mods {
		mod(&opts)
	}

	// Enforce the MaxSessions cap before doing any (expensive) engine work so a
	// full manager rejects creation cheaply with a typed 429 error.
	m.mu.RLock()
	atLimit := m.maxSessions > 0 && len(m.sessions) >= m.maxSessions
	requireCap := m.requireCap
	m.mu.RUnlock()
	if atLimit {
		return nil, protocol.ErrSessionLimitReached
	}

	// Hybrid sessions (improvement-plan item 31) come from pre-supplied engines
	// (engine.WithEngines) or by instantiating one engine per requested platform
	// (opts.Platforms). Both bypass the single-engine path below.
	if len(opts.Engines) > 0 {
		return m.registerMultiEngineSession(opts.Engines, kind, opts)
	}
	if len(opts.Platforms) > 0 {
		engines, err := m.buildEnginesForPlatforms(opts.Platforms, opts)
		if err != nil {
			return nil, err
		}
		return m.registerMultiEngineSession(engines, kind, opts)
	}

	eng, err := engine.New(kind, opts)
	if err != nil {
		return nil, err
	}

	id := uuid.New().String()
	now := time.Now()
	s := &Session{
		ID:               id,
		Kind:             kind,
		Engine:           eng,
		Events:           NewEventBus(0),
		CreatedAt:        now,
		Persistent:       opts.Persistent,
		ConsoleRingLimit: 500,
		LastActivity:     now,
		Limits:           m.limits,
	}
	if requireCap {
		s.Capability = newSessionCapability()
	}

	// Engines that implement SetSession learn their sandbox session id: Android
	// screenshots/logcat land under <trace>/sessions/<session>/ (item 30), and
	// Chrome names its bundled trace archive <trace>/<session>.spz (item 24).
	if s, ok := eng.(interface{ SetSession(string) }); ok {
		s.SetSession(id)
	}

	// Browser sessions get an action timeline recorder so every step is
	// captured to an append-only JSONL stream. A recorder failure (e.g. an
	// unwritable trace dir) must not prevent the session from being created.
	if kind == engine.KindChrome {
		rec, rerr := browser.NewActionRecorder(os.Getenv(browser.TraceDirEnv), id)
		if rerr != nil {
			slog.Warn("sandbox: action timeline recorder unavailable",
				"session_id", id, "err", rerr)
		} else {
			s.Recorder = rec
			// Register the recorder with the engine so the CDP event loop can
			// capture runtime exceptions into the timeline.
			eng.AddListener(rec.Listener())
		}
	}

	// Feed raw platform events into the session's typed event bus
	// (improvement-plan item 34). The translator runs in the engine's event
	// loop; the bus fan-out drops on overflow so it never blocks the engine.
	eng.AddListener(browser.NewEventPublisher(s.Events.Publish))

	m.mu.Lock()
	m.sessions[id] = s
	hook := m.sessionCreated
	m.mu.Unlock()

	if hook != nil {
		hook(id)
	}

	return s, nil
}

// registerMultiEngineSession wires pre-built engines into a hybrid session
// (improvement-plan item 31): it picks a default active context, binds each
// engine to the sandbox session id (so Android screenshots / Chrome traces land
// in the right place), attaches an action timeline recorder to the web engine,
// and registers the session in the manager.
func (m *Manager) registerMultiEngineSession(engines map[string]engine.Engine, kind engine.Kind, opts engine.Options) (*Session, error) {
	id := uuid.New().String()
	now := time.Now()
	active := defaultActiveContext(engines)
	s := &Session{
		ID:               id,
		Kind:             kind,
		Engines:          engines,
		ActiveContext:    active,
		Engine:           engines[active],
		Events:           NewEventBus(0),
		CreatedAt:        now,
		Persistent:       opts.Persistent,
		ConsoleRingLimit: 500,
		LastActivity:     now,
		Limits:           m.limits,
	}
	if m.capRequired() {
		s.Capability = newSessionCapability()
	}

	// Bind every engine to the sandbox session id so per-session recordings
	// (Android screenshots/logcat, Chrome .spz archives) key on the same id.
	for _, eng := range engines {
		if setter, ok := eng.(interface{ SetSession(string) }); ok {
			setter.SetSession(id)
		}
		// Feed each context's raw platform events into the shared session bus
		// (improvement-plan item 34); the translator is a no-op for platforms
		// whose events are not CDP.
		eng.AddListener(browser.NewEventPublisher(s.Events.Publish))
	}

	// The web context gets the action timeline recorder so hybrid sessions keep
	// the same step-by-step JSONL stream as single Chrome sessions.
	if kind == engine.KindChrome {
		if web, ok := engines["web"]; ok {
			rec, rerr := browser.NewActionRecorder(os.Getenv(browser.TraceDirEnv), id)
			if rerr != nil {
				slog.Warn("sandbox: action timeline recorder unavailable",
					"session_id", id, "err", rerr)
			} else {
				s.Recorder = rec
				web.AddListener(rec.Listener())
			}
		}
	}

	m.mu.Lock()
	m.sessions[id] = s
	hook := m.sessionCreated
	m.mu.Unlock()

	if hook != nil {
		hook(id)
	}

	return s, nil
}

// buildEnginesForPlatforms instantiates one engine per requested platform
// context (improvement-plan item 31), creating them in sorted order so a
// mid-way failure closes only the engines built so far. Each context maps to an
// engine kind via kindForContext ("web" -> Chrome, "android" -> Android).
func (m *Manager) buildEnginesForPlatforms(platforms []string, opts engine.Options) (map[string]engine.Engine, error) {
	engines := make(map[string]engine.Engine, len(platforms))
	order := append([]string(nil), platforms...)
	sort.Strings(order)
	for _, name := range order {
		eng, err := engine.New(kindForContext(name), opts)
		if err != nil {
			// Close everything built so far so a failed hybrid creation leaks
			// nothing.
			for _, e := range engines {
				e.Close()
			}
			return nil, fmt.Errorf("platform %q: %w", name, err)
		}
		engines[name] = eng
	}
	return engines, nil
}

// newSessionCapability generates the per-session owner secret (improvement-plan
// item 35): 16 random bytes hex-encoded. crypto/rand failure is unrecoverable in
// practice; a time-based uuid is the fallback so session creation never hard-fails.
func newSessionCapability() string {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return uuid.NewString()
	}
	return hex.EncodeToString(b)
}

// kindForContext maps a hybrid context name to the engine kind that backs it
// (improvement-plan item 31): "web" -> Chrome, "android" -> Android, anything
// else -> Chrome (the default platform).
func kindForContext(name string) engine.Kind {
	if name == "android" {
		return engine.KindAndroid
	}
	return engine.KindChrome
}

// defaultActiveContext picks the initial active context of a hybrid session:
// "web" when present, else "android", else the first name in sorted order.
func defaultActiveContext(engines map[string]engine.Engine) string {
	if _, ok := engines["web"]; ok {
		return "web"
	}
	if _, ok := engines["android"]; ok {
		return "android"
	}
	names := make([]string, 0, len(engines))
	for name := range engines {
		names = append(names, name)
	}
	sort.Strings(names)
	if len(names) > 0 {
		return names[0]
	}
	return ""
}

// GetSession retrieves an active session by ID.
func (m *Manager) GetSession(id string) (*Session, bool) {
	m.mu.RLock()
	defer m.mu.RUnlock()
	s, ok := m.sessions[id]
	return s, ok
}

// DeleteSession shuts down the engine and removes the session from the map.
func (m *Manager) DeleteSession(id string) error {
	m.mu.Lock()
	s, ok := m.sessions[id]
	var hook func(sessionID string)
	if ok {
		delete(m.sessions, id)
		hook = m.sessionDestroyed
	}
	m.mu.Unlock()

	// Close outside the lock so a slow driver doesn't stall other operations.
	if !ok {
		return fmt.Errorf("session not found")
	}

	if hook != nil {
		hook(id)
	}

	s.Close()
	return nil
}

// Close shuts down the session, flushing and closing the action timeline
// recorder (if any) before closing every engine. For hybrid sessions it closes
// each context's engine; the active-context mirror (Engine) is one of those, so
// it is never closed twice. Safe to call once.
func (s *Session) Close() {
	if s.Recorder != nil {
		if err := s.Recorder.Close(); err != nil {
			slog.Warn("sandbox: closing action timeline recorder",
				"session_id", s.ID, "err", err)
		}
	}
	s.ctxMu.Lock()
	var engines []engine.Engine
	if len(s.Engines) > 0 {
		seen := make(map[engine.Engine]bool, len(s.Engines))
		for _, eng := range s.Engines {
			if seen[eng] {
				continue
			}
			seen[eng] = true
			engines = append(engines, eng)
		}
	} else if s.Engine != nil {
		engines = append(engines, s.Engine)
	}
	s.ctxMu.Unlock()
	for _, eng := range engines {
		eng.Close()
	}
}
